
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "tinymce": "../../../../tinymce",
  "Ext.ux.form.field.BoxSelect": "../../../../ext/src/ux/form/field/BoxSelect1.js",
  "Ext.rtl.EventObjectImpl": "../../../../ext/src/rtl/EventObject.js",
  "SWPCommon": "../../../common",
  "SWPCommon.lib.AwesomeModel": "../../../common/lib/AwesomeUploader.js",
  "SWPCommon.lib.AwesomeStore": "../../../common/lib/AwesomeUploader.js",
  " Ext.Msg": "../../../../ext/src/window/MessageBox.js",
  "Ext": "../../../../ext/src",
  "Ext.ux.layout.component.field.BoxSelectField": "../../../../ext/src/ux/form/field/BoxSelect.js",
  "Mobile": "../../../../ext/src/ux/view/animated-dataview.js",
  "SWP": "../../../common",
  "Ext.ux.BoxSelect.Item": "../../../../ext/src/ux/form/field/BoxSelect1.js",
  "ImageModel": "../../../../ext/src/ux/view/data-view.js",
  "CHAT": "../../app",
  "CHAT.view.TinyMCETextAreaWindowManager": "../../app/view/TinyMCETextArea.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "CHAT.model.ThreadCatogery": [],
  "CHAT.model.TaskStatus": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "SWPCommon.view.BadgeTabPanel": [],
  "Ext.ux.layout.component.field.BoxSelectField": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.BoxSelect.Item": [],
  "Ext.ux.DataView.DragSelector": [],
  "SWPCommon.view.BadgeTab": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "CHAT.store.ThreadCatogery": [],
  "CHAT.view.MessageWindow": [],
  "CHAT.controller.TrainingTools": [],
  "CHAT.view.GroupingBtn": [],
  "SWPCommon.lib.AwesomeStore": [],
  "Ext.ux.PreviewPlugin": [],
  "SWPCommon.lib.AwesomeUploader": [],
  "CHAT.store.User": [],
  "SWPCommon.model.File": [],
  "CHAT.view.ImageButton": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "CHAT.view.TinyMCETextAreaWindowManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "CHAT.view.GroupingList": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "CHAT.store.Posts": [],
  "CHAT.store.Reference": [],
  "Ext.ux.event.Recorder": [],
  "SWPCommon.lib.AwesomeModel": [],
  "CHAT.view.PostHeader": [],
  "SWP.lib.FeedValidator": [],
  "CHAT.model.Reference": [],
  "CHAT.view.Post": [],
  "Ext.ux.ajax.SimManager": [],
  "CHAT.model.TaskAction": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "SWPCommon.model.TaskStatus": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "CHAT.model.Message": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "SWPCommon.view.BadgeButton": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "SWPCommon.view.workfiles.WorkFiles": [],
  "Ext.ux.TreePicker": [],
  "CHAT.view.TinyMCETextArea": [],
  "CHAT.view.Reply": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "CHAT.model.Post": [],
  "CHAT.view.BadgeButton": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "CHAT.view.DownloadAttachment": [],
  "CHAT.view.Viewport": [],
  "CHAT.view.GroupingComboBox": [],
  "Ext.ux.FieldReplicator": [],
  "CHAT.Application": [],
  "SWPCommon.view.TableView": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "CHAT.store.Messages": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.XHRUpload": [],
  "CHAT.view.DownloadAttachments": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "SWPCommon.FlexcrollAbstractComponent": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "SWPCommon.store.TaskActions": [],
  "Ext.ux.DataView.Animated": [],
  "CHAT.view.DataList": [],
  "Ext.ux.form.field.BoxSelect": [],
  "SWPCommon.view.workfiles.FilesGrid": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "CHAT.view.SearchField": [],
  "tinymce.WindowManager": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "CHAT.view.QuotedText": [],
  "Ext.ux.event.Player": [],
  "SWPCommon.store.TaskStatuss": [],
  "CHAT.model.User": [],
  "CHAT.store.TaskActions": [],
  "CHAT.view.NewTopicWindow": [],
  "CHAT.view.BadgeTab": [],
  "CHAT.view.Paging": [
    "Ext.PagingToolbar"
  ],
  "CHAT.view.FbarButton": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "CHAT.view.TabView": [],
  "SWPCommon.model.TaskAction": [],
  "CHAT.view.NewTopic": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "CHAT.store.TaskStatuss": [],
  "Ext.ux.DataTip": [],
  "CHAT.view.BadgeTabPanel": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "SWPCommon.view.workfiles.UploadPopup": [],
  "CHAT.view.MessageDetails": [],
  "SWPCommon.model.Message": []
});
Ext.ClassManager.addNameAliasMappings({
  "CHAT.model.ThreadCatogery": [],
  "CHAT.model.TaskStatus": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "SWPCommon.view.BadgeTabPanel": [
    "widget.badgetabpenl"
  ],
  "Ext.ux.layout.component.field.BoxSelectField": [
    "layout.boxselectfield"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.BoxSelect.Item": [],
  "Ext.ux.DataView.DragSelector": [],
  "SWPCommon.view.BadgeTab": [
    "widget.badgetab"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "CHAT.store.ThreadCatogery": [],
  "CHAT.view.MessageWindow": [
    "widget.messagewindow"
  ],
  "CHAT.controller.TrainingTools": [],
  "CHAT.view.GroupingBtn": [
    "feature.groupingbtn"
  ],
  "SWPCommon.lib.AwesomeStore": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "SWPCommon.lib.AwesomeUploader": [
    "widget.awesomeuploader"
  ],
  "CHAT.store.User": [],
  "SWPCommon.model.File": [],
  "CHAT.view.ImageButton": [
    "widget.imagebutton"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "CHAT.view.TinyMCETextAreaWindowManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "CHAT.view.GroupingList": [
    "widget.groupinglist"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "CHAT.store.Posts": [],
  "CHAT.store.Reference": [],
  "Ext.ux.event.Recorder": [],
  "SWPCommon.lib.AwesomeModel": [],
  "CHAT.view.PostHeader": [
    "widget.postheader"
  ],
  "SWP.lib.FeedValidator": [],
  "CHAT.model.Reference": [],
  "CHAT.view.Post": [
    "widget.post"
  ],
  "Ext.ux.ajax.SimManager": [],
  "CHAT.model.TaskAction": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "SWPCommon.model.TaskStatus": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "CHAT.model.Message": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "SWPCommon.view.BadgeButton": [
    "widget.badgebutton"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "SWPCommon.view.workfiles.WorkFiles": [
    "widget.workfiles"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "CHAT.view.TinyMCETextArea": [
    "widget.tinymce_field",
    "widget.tinymce_textarea"
  ],
  "CHAT.view.Reply": [
    "widget.reply"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "CHAT.model.Post": [],
  "CHAT.view.BadgeButton": [
    "widget.badgebutton"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "CHAT.view.DownloadAttachment": [
    "widget.downloadattachment"
  ],
  "CHAT.view.Viewport": [],
  "CHAT.view.GroupingComboBox": [
    "widget.groupingcombo",
    "widget.groupingcombobox"
  ],
  "Ext.ux.FieldReplicator": [],
  "CHAT.Application": [],
  "SWPCommon.view.TableView": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "CHAT.store.Messages": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.XHRUpload": [],
  "CHAT.view.DownloadAttachments": [
    "widget.downloadattachments"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "SWPCommon.FlexcrollAbstractComponent": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "SWPCommon.store.TaskActions": [],
  "Ext.ux.DataView.Animated": [],
  "CHAT.view.DataList": [
    "widget.datalist"
  ],
  "Ext.ux.form.field.BoxSelect": [
    "widget.boxselect"
  ],
  "SWPCommon.view.workfiles.FilesGrid": [
    "widget.filesgrid"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "CHAT.view.SearchField": [
    "widget.searchfield"
  ],
  "tinymce.WindowManager": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "CHAT.view.QuotedText": [
    "widget.quotedtext"
  ],
  "Ext.ux.event.Player": [],
  "SWPCommon.store.TaskStatuss": [],
  "CHAT.model.User": [],
  "CHAT.store.TaskActions": [],
  "CHAT.view.NewTopicWindow": [
    "widget.newtopicwindow"
  ],
  "CHAT.view.BadgeTab": [
    "widget.badgetab"
  ],
  "CHAT.view.Paging": [
    "widget.pagingtoolbar"
  ],
  "CHAT.view.FbarButton": [
    "widget.fbarbutton"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "CHAT.view.TabView": [
    "widget.tabview"
  ],
  "SWPCommon.model.TaskAction": [],
  "CHAT.view.NewTopic": [
    "widget.newtopic"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "CHAT.store.TaskStatuss": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "CHAT.view.BadgeTabPanel": [
    "widget.badgetabpenl"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "SWPCommon.view.workfiles.UploadPopup": [
    "widget.UploadPopup"
  ],
  "CHAT.view.MessageDetails": [
    "widget.messagedetails"
  ],
  "SWPCommon.model.Message": []
});
