<?php
/**
 * Auto generated by prado-cli.php on 2008-03-04 08:00:10.
 */
class AttributeValueRecord extends AttributeValueAR
{

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>