<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class AttributeTypeAR extends FActiveLangRecord
{
	const TABLE='attributes_types';

	public $uid;
	public $name;
	public $editor;
    public $renderer;
    public $i18n=1;
    public $formater='';

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>