<?php
/**
 * Auto generated by prado-cli.php on 2008-03-04 07:59:30.
 */
class AttributeAR extends FActiveLangRecord
{
	const TABLE='attributes';

    public $uid;
    public $product_id;
    public $value;
    public $definition_uid;
    public $price_add=0;
    public $price_coef=1;
    public $price=0;
    public $is_enabled=1;
    public $is_default=0;
    public $discr = 'attribute';
    public $ordering = 0;


    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>