<?php

/**
 * Auto generated by prado-cli.php on 2008-03-04 07:59:30.
 */
class AttributeViewRecord extends AttributeViewAR implements FActiveTypedRecord {

    static $_type_defs;

    public function getTypeFormat() {
        if (self::$_type_defs === null) {
            self::$_type_defs = array();
            $td = AttributeTypeRecord::finder()->findAll();
            foreach ($td as $t) {
                self::$_type_defs[$t->uid] = $t->formater;
            }
        }
        return $this->_type_defs[$this->type];
    }

    public function getNameVariant($c='') {
        if (!$c)
            $c = FU::Culture();
        $var = 'nameLang' . $c;
        return $this->$var;
    }

    public function getValueFormated($c='') {

        $val = $this->value;

        if ($f = $this->getTypeFormat())
            return call_user_func(array('AttributeTypeRecord', $f), $val);
        else
            return $val;
    }

    public static function finder($className=__CLASS__) {
        return parent::finder($className);
    }

}
