<?php
/**
 * Auto generated by prado-cli.php on 2008-03-04 08:00:10.
 */
class AttributeValueAR extends FBaseActiveRecord
{
	const TABLE='attribute_values';
 /*   public static $COLUMN_MAPPING=array
    (
        'uid'=>'Uid',
        'attributes_uid'=>'AttributeUid',
        'lang'=>'Lang',
        'value'=>'Value'
    );
*/

	/**
	 * @var integer $Uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var string $Lang
	 * @soapproperty
	 */
	public $lang;

	/**
	 * @var string $Value
	 * @soapproperty
	 */
	public $value;

	/**
	 * @var integer $attributes_uid
	 * @soapproperty
	 */
	public $attributes_uid;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>