<?php
/**
 * Auto generated by prado-cli.php on 2008-03-04 07:59:55.
 */
class AttributeNameRecord extends AttributeNameAR
{

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>