<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 11:19:51.
 */
class AttributeNameViewAR extends TActiveRecord
{
	const TABLE='view_attribute_names';
    public static $COLUMN_MAPPING=array
    (
        'overlays_uid'=>'OverlayUid',
        'attributes_uid'=>'AttributeUid',
        'lang'=>'Lang',
        'name'=>'Name'
    );

	public $overlays_uid;
	public $attributes_uid;
	public $name;
	public $lang;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>