<?php
/**
 * Auto generated by prado-cli.php on 2008-07-10 10:54:44.
 */
class CategoryAR extends FOrderedTreeActiveRecord implements FActiveTypedRecord//FActiveLangRecord
{
	const TABLE='categories';

	public $uid;
	public $user_id;
	public $key;
	public $data;
	public $created;
	public $updated;
	public $name;
	public $description;
	public $read_level;
	public $write_level;
	public $parent_id;
	public $is_folder;
	public $deleted=0;
	public $ordering;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
