<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 11:08:43.
 */
class CurrencyAR extends FBaseActiveRecord
{
	const TABLE='cms_currencies';

	public $uid;
	public $culture;
	public $currency;
	public $currency_local;
	public $conversion;
	public $precision;
	public $leftside=1;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>