<?php
/**
 * Auto generated by prado-cli.php on 2008-10-13 12:51:06.
 */
class FLogAR extends FBaseActiveRecord
{
	const TABLE='cms_log';

	public $uid;
        public $created;
	public $be_user_id;
	public $domain;
	public $record_id;
	public $value;
        public $difference='';

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}