<?php
/**
 * Auto generated by prado-cli.php on 2008-04-20 01:05:07.
 */
class MessageCatalogueRecord extends MessageCatalogueAR
{
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>