<?php
/**
 * Auto generated by prado-cli.php on 2008-04-16 11:43:45.
 */
class NewsImagesRecord extends NewsImagesAR
{

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public function getExtension() {
							
		return strtolower(pathinfo($this->uid, PATHINFO_EXTENSION));
		
	}
	
	
	public function getIsImage()
	{
	    $p = strtolower(pathinfo($this->uid, PATHINFO_EXTENSION));
	    $imgs = array('gif','png','jpg');
	    if (array($p,$imgs)===false)
		return false;

	    return true;
	}

	public function getPreviewSrc()
	{
	    if ($this->getIsImage())
		return $this->uidAsThumb120x400;
	    else
		return Prado::getPathOfNamespace('JS.desktop.resources.images.LinspireClear.48x48.mimetypes.document','.png');
	}


}
?>