<?php
/**
 * Auto generated by prado-cli.php on 2008-04-16 12:58:06.
 */
class QAAR extends FBaseActiveRecord
{
	const TABLE='cms_qa';

	public $uid;
	public $input_date;
	public $question;
	public $answer;
	public $publish_date;
	public $lang='cs';
	public $contact='';

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>