<?php
/**
 * Auto generated by prado-cli.php on 2008-04-20 01:04:37.
 */
class TranslationAR extends FBaseActiveRecord
{
	const TABLE='trans_unit';
    public static $COLUMN_MAPPING=array
    (
        'msg_id'=>'uid',
        'target'=>'target'
    );

	public $uid;
	public $cat_id;
	public $id=0;
	public $source;
	public $target;
	public $comments='';
	public $date_added=0;
	public $date_modified=0;
	public $author=0;
	public $translated=0;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>