<?php
/**
 * Auto generated by prado-cli.php on 2008-03-04 08:00:10.
 */
class ValueIndexAR extends FBaseActiveRecord
{
	const TABLE='value_index';

	/**
	 * @var integer $Uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var string $Lang
	 * @soapproperty
	 */
	public $lang;

	/**
	 * @var string $Value
	 * @soapproperty
	 */
	public $value;

	/**
	 * @var integer $attributes_uid
	 * @soapproperty
	 */
	public $source='';

	public $domain='';
    
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>