<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class AttributeTypeRecord extends AttributeTypeAR
{
	const TABLE='attribute_types';

    public static function locations($val)
    {
        return 'České Budějovice';
    }
    
    public static function dateFormatShort($val)
    {
        return self::dateFormat($val,'D');
    }
    public static function booleanFormat($val)
    {
        $cls = 'x-grid3-check-col';
        if ($val === "1" || $val === true) {
            $cls .= '-on';
        }
        else {
            $cls .= '-null';
        }
        return '<div class="'.$cls.'" style="background-position: right"></div>';
    }
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>