<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class AttributeDefinitionAR extends FActiveLangRecord
{
	const TABLE='attributes_definitions';

	public $uid;
	public $name;
	public $type;
    public $primary=0;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
