<?php
/**
 * Auto generated by prado-cli.php on 2008-03-04 07:59:30.
 */
class AttributeRecord extends AttributeAR 
{
    private $_type;
    private $_name;
    private $_Selected=0;

    public function select()
    {
        $this->_Selected = true;
    }

    public function getSelected() 	{
        return $this->_Selected;
    }

    public function setSelected($value) 	{
        $this->_Selected = $value;
    }

/*
	const TABLE='attributes';
    private $_name = null;
    private $_value = null;


    public function getName()
    {
       if ($this->_name === null)
       {
           
           $names = AtributeNameRecord::finder()->findAllByAttributeUid($this->Uid);
           $this->_name = FU::langFind($names)->Name;
       }
       return $this->_name;
    }
    
    
    public function getValue()
    {
       if ($this->_value === null)
       {
           $values = AttributeNameViewRecord::finder()->findAllByAttributeUid($this->Uid);
           $this->_name = FU::langFind($values)->Value;
       }
       return $this->_value;
    }

*/
    public function setType($val) {
        $this->_type = $val;
    }
    public function getType() {
        return $this->_type;
    }
    
    public function setName($val) {
        $this->_name = $val;
    }
    public function getName() {
       if ( !$this->_name)
                $this->_name = AttributeDefinitionRecord::finder ()->findByPk ($this->definition_uid)->name;
        return $this->_name;
    }

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}