<?php
/**
 * Auto generated by prado-cli.php on 2008-03-04 07:59:55.
 */
class AttributeNameAR extends TActiveRecord
{
	const TABLE='attribute_names';
    public static $COLUMN_MAPPING=array
    (
        'overlays_uid'=>'OverlayUid',
        'attributes_uid'=>'AttributeUid'
    );



	/**
	 * @var integer $OverlaysUid
	 * @soapproperty
	 */
	public $OverlayUid;

	/**
	 * @var integer $AttributeUid
	 * @soapproperty
	 */
	public $AttributeUid;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>