<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 12:57:58.
 */
class CartAR extends FBaseActiveRecord
{
	const TABLE='cms_cart';

	public $uid;
	public $data;
	public $changed;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>