<?php
/**
 * Auto generated by prado-cli.php on 2008-07-10 10:54:44.
 */
class CategoryRecord extends CategoryAR implements FTypedActiveRecord
{
    const DETAIL_PAGE = 'ShopCategoryPage';
	protected $_typedata;
	
	public static $RELATIONS=array
    (
       // 'children' => array(self::HAS_MANY, 'CategoryRecord', 'parent_id'),
        'parent' => array(self::BELONGS_TO, 'CategoryRecord', 'parent_id'),
		'products'=>array(self::MANY_TO_MANY, 'ProductRecord', 'products_categories','(1=1) ORDER BY ordering ASC')
    );


	public function getChildren()
	{
		$p = $this->products;
		if (!$p)
		{
			$c = new TActiveRecordCriteria;
			$c->setCondition('parent_id = :id');
			$c->Parameters[':id'] = $this->uid;
			$c->OrdersBy['ordering']='ASC';
			$p = $this->finder()->findAll($c);
		}
		
		return $p;
	}
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public function getIsFolder() 
	{
		return $this->is_folder;
	}
	
	public function setIsFolder($value) 
	{
		$this->is_folder = $value;
	}
	
    public function getSortName() 
    {
        if ($this->name == 'Recycle Bin')
            return 'zzzzzzzzzzzzzz';
        else    
            return $this->name;
    }
    
    public function getMenuType() 
    {
        if ($this->name == 'Recycle Bin')
            return 'recycleBin';
        elseif ($this->is_folder)
            return 'folder';
        else    
            return 'any';
    }

    public function getNodeType() 
    {
        if ($this->uid == 1)
            return 'recycleBin';
        elseif ($this->is_folder)
            return 'folder';
        else    
            return 'leaf';
    }

    public function getSortLeaf() 
    {
        if ($this->name == 'Recycle Bin')
            return true;
        else
            return !$this->is_folder;
    }

	public function getType() 
	{
		$types = TypeRecord::getTypes();
		return $types[self::DETAIL_PAGE];
	}

	public function getCatID()
	{
		return sprintf('%03d',$this->uid).'-'.FU::urlify($this->NameLangAct);
		return $this->uid;
	}	
	public function getTypeData($inherit = false)
	{
		
		if ($this instanceof FTypedActiveRecord)
		{
			if ($this->_typedata === null)
			{
				if ($inherit) {
						$parent = $this->parent;
						$typeData = $parent->type->data+$this->type->data;
				} else {
						$typeData = $this->type->data;
				}
				$typeData['name'] = $this->type->name;
				$this->_typedata = $typeData;
			}
			return $this->_typedata;
			
		} else {
			return array();
		}
	}
	
	public function setTypeData($key, $value)
	{
		if ($this instanceof FTypedActiveRecord && $key)
		{
			$this->type->data[$key] = $value;
		}	
	}
	
	public function unsetTypeData($key)
	{
		if ($this instanceof FTypedActiveRecord && $key)
		{
			unset($this->type->data[$key]);
		}	
	}

	public function getHref($inherit = false,$par=array())
	{
		if ($this->getCatID())
		{
	   		$typeData = $this->getTypeData();
			$params  = (is_array($typeData['pageParams']))?$typeData['pageParams']:array();
			$params = array_merge($params,$par);
			$params['catid']=$this->getCatID();
			return Prado::getApplication()->getRequest()->constructUrl('page',$typeData['pagePath'],$params);
		}
		else
			return null;
	}
	
	public function setNameLang($value,$culture)
	{
	}

	public function getNameLang($culture)
	{
		$g =  Prado::getApplication()->getGlobalization();
		$oc = $g->getCulture();
		$g->setCulture(strtolower($culture));
		$val =  Prado::localize($this->name);
		$g->setCulture(strtolower($oc));
		return $val;
		
	}
	

}
