<?php
/**
 * Auto generated by prado-cli.php on 2010-02-15 03:42:08.
 * generateAll Application.model.schema . soap F AR
 * generate table Application.model.schema.CLASS
 */
class DefinitionAR extends FActiveLangRecord
{
	const TABLE='definitions';


	/**
	 * @var integer $_uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var string $_class
	 * @soapproperty
	 */
	public $class;

	/**
	 * @var string $_name
	 * @soapproperty
	 */
	public $name;

	/**
	 * @var string $_value
	 * @soapproperty
	 */
	public $value;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}