<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 11:08:43.
 */
class LanguageAR extends FBaseActiveRecord
{
	const TABLE='cms_languages';

	public $uid;
	public $lang;
	public $name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>