<?php
/**
 * Auto generated by prado-cli.php on 2008-04-16 12:58:06.
 */
class MailingRecord extends NewsletterAR
{
	const TABLE="cms_mailings";
	
	public function getHref($par=array())
	{
		if ($container = Prado::getApplication()->Modules['cms']->getContainer('mailing'))
		{
			$par['catid']=$this->getCatID();
			//echo $this->getCatID().'<br>'.$container->getHref(false,$par);
			
			return Prado::getApplication()->Parameters['newsletterHostname'].$container->getHref(false,$par);
		}
		return '#';
	}


	public function getAuthorDefault()
	{
		return ($this->author)?$this->author : Prado::getApplication()->User->Name;
	}
	
	public function setAuthorDefault($value)
	{
		$this->author = $value;
	}

	public function getCoolUrl()
	{
		return ($this->url)?$this->url : FU::urlify($this->name);
	}
	
	public function setCoolUrl($value)
	{
		$this->url = FU::urlify($value);
	}

	public function getCatID()
	{
		return sprintf('%03d',$this->uid).'-'.$this->CoolUrl;//FU::urlify($this->name);
	}
	
	
	public function getProcessedText()
	{
	}

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>