<?php
/**
 * Auto generated by prado-cli.php on 2008-04-16 11:43:45.
 */
class NewsImagesAR extends FBaseActiveRecord
{
	const TABLE='news_images';

	public $uid;
	public $news_uid;
	public $objects_uid;
	public $text;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>