<?php
/**
 * Auto generated by prado-cli.php on 2008-04-16 12:58:06.
 */
class QARecord extends QAAR
{
    public function getPerex($text) {
        
        //$text = str_ireplace(array('Dobrý den','Dobry den'),'',$text);

        $words = explode(' ',trim($text));
		$trail = (count($words)>6)?'...':'';
        return implode(' ',array_slice($words,0,5)).$trail;
    }
    
	public function getAnswerPerex()
	{
		return $this->getPerex($this->answer);
	}
    
	public function getQuestionPerex()
	{
		return $this->getPerex($this->question);
	}

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>