<?php
/**
 * Auto generated by prado-cli.php on 2010-02-15 03:42:08.
 * generateAll Application.model.schema . soap F AR
 * generate table Application.model.schema.CLASS
 */
class RoleAR extends FBaseActiveRecord
{
	const TABLE='roles';


	/**
	 * @var integer $_uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var string $_name
	 * @soapproperty
	 */
	public $name;

	/**
	 * @var string $_policy
	 * @soapproperty
	 */
	public $policy;

	/**
	 * @var integer $_parent_id
	 * @soapproperty
	 */
	public $parent_id;

	/**
	 * @var string $_description
	 * @soapproperty
	 */
	public $description;
        public $level;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}