<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 * 
 * ALTER TABLE `c1_video`.`active_url` ADD COLUMN `instructor_id` INT(11) NULL  AFTER `alreadyplayed` , ADD COLUMN `student_id` INT(11) NULL  AFTER `instructor_id` ;

 */
class ActiveUrlAR extends FBaseActiveRecord
{
	const TABLE='active_url';

	public $uid;
	public $url;
	public $user_id;
	public $content_id;
	public $product_id;
	public $activated;
	public $expire;
	public $alreadyplayed ; 
	public $instructor_id;
	public $student_id;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}