<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 11:32:57.
 */
class AddressAR extends FBaseActiveRecord
{
	const TABLE='addresses';

	public $Uid;
	public $UserId;
	public $CompanyName='';
	public $CustomerName;
	public $IC='';
	public $DIC='';
	public $Street='';
	public $StreetNumber='';
	public $Zip='';
	public $City='';
	public $Email='';
	public $Phone='';
	public $Comment='';
	public $Changed=0;
	public $SendNewsletter=1;
	public $Active=1;
	public $Type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>