<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class AdZoneAR extends FBaseActiveRecord
{
	const TABLE='video_ads';

	public $uid;
	public $videos_id;
	public $zone;
	public $name='';
	public $start=0;
	public $duration=0;
        public $is_enabled=1;
        public $position='';

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
