<?php
/**
 * Auto generated by prado-cli.php on 2010-02-15 03:42:07.
 * generateAll Application.model.schema . soap F AR
 * generate table Application.model.schema.CLASS
 */
class BranchUserAR extends FBaseActiveRecord
{
	const TABLE='tree_branch_users';


	/**
	 * @var integer $_uid
	 * @soapproperty
	 */
	public $uid;
        public $child_id;
	/**
	 * @var string $_name
	 * @soapproperty
	 */
	public $name;

	/**
	 * @var string $_parent_id
	 * @soapproperty
	 */
	public $parent_id;

        public $t;
        
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}