<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class BusinessEventsAR extends FBaseActiveRecord
{
	const TABLE='business_events';

	public $id;
	public $event_name;
	public $event_date;
	public $process_status;
	public $table_type;
    public $data;

    public static function finder($className=__CLASS__) {
		return parent::finder($className);
	}
}
