<?php
/**
 * Auto generated by prado-cli.php on 2008-01-23 12:04:58.
 */
class ClientAR extends FBaseActiveRecord
{
	const TABLE='knt_clients';

	public $Uid;
	public $Email;
	public $Name;
        public $Firstname;
        public $Surname;
	public $DateOfBirth;
	public $Phone;
	public $Created;
	public $Updated;
        public $branch_id;
        public $be_user_id;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
