<?php
/**
 * Auto generated by prado-cli.php on 2008-04-16 12:58:06.
 */
class CommentAR extends FBaseActiveRecord
{
	const TABLE='ch_comments';

	public $uid;
	public $input_date;
	public $comment;
	public $lang='cs';
	public $contact='';
        public $fe_user_id;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>