<?php
/**
 * Auto generated by prado-cli.php on 2010-02-02 01:01:57.
 * generateAll Application.model.schema . soap F AR
 * generateRec table Application.model.schema.CLASS
 */
class ContactRecord extends ContactAR
{

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}