<?php
/**
 * Auto generated by prado-cli.php on 2010-02-15 03:42:07.
 * generateAll Application.model.schema . soap F AR
 * generate table Application.model.schema.CLASS
 */
class ContactAR extends FBaseActiveRecord
{
	const TABLE='contacts';


	/**
	 * @var integer $_uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var integer $_user_id
	 * @soapproperty
	 */
	public $user_id;

	/**
	 * @var integer $_user_address_id
	 * @soapproperty
	 */
	public $user_address_id;

	/**
	 * @var integer $_contact_person_id
	 * @soapproperty
	 */
	public $contact_person_id;

	/**
	 * @var integer $_type
	 * @soapproperty
	 */
	public $type;

	/**
	 * @var string $_value
	 * @soapproperty
	 */
	public $value;

	/**
	 * @var string $_create_date
	 * @soapproperty
	 */
	public $create_date;

	/**
	 * @var integer $_create_by
	 * @soapproperty
	 */
	public $create_by;

	/**
	 * @var string $_update_date
	 * @soapproperty
	 */
	public $update_date;

	/**
	 * @var integer $_update_by
	 * @soapproperty
	 */
	public $update_by;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}