<?php
/**
 * Auto generated by prado-cli.php on 2010-02-02 01:01:57.
 * generateAll Application.model.schema . soap F AR
 * generateRec table Application.model.schema.CLASS
 */
class ContactPersonRecord extends ContactPersonAR
{
    private $_contacts;

    public function getName()
    {
        $suffix = ($this->name_suffix) ? ', '.$this->name_suffix : '';
        return trim($this->name_prefix.' '.$this->first_name.' '.$this->surname).$suffix;
    }


    public function getContacts()
    {
        if ($this->_contacts === null)
        {
            $recs = ContactRecord::finder()->findAll('contact_person_id = ?',$this->uid);
            foreach($recs as $rec)
            {
                $this->_contacts[] = array('name'=>$rec->type,'value'=>$rec->value);
            }
        }
        return json_encode($this->_contacts);
    }

    public function setContacts($value)
    {

        $c = json_decode($value,true);

        if (!$c) return;

        ContactRecord::finder()->deleteAll('contact_person_id = ?',$this->uid);

        foreach($c as $contact)
        {
            $cc = new ContactRecord();
            $cc->type = $contact['name'];
            $cc->value = $contact['value'];
            $cc->contact_person_id = $this->uid;
            $cc->user_id = $this->user_id;
            $cc->save();
        }
    }




    public function setName($value) {}


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}