<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class CourseContentAR extends FBaseActiveRecord
{
	const TABLE='products_videos';

	public $uid;
	public $product_id;
	public $video_id;
	public $ordering=0;
	public $type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}


}
