<?php
/**
 * Auto generated by prado-cli.php on 2013-08-12 01:03:11.
 */
class CourseDetailsRecord extends CourseDetailsAR
{
	public static function finder($className=__CLASS__)	{
		return parent::finder($className);
	}
}