<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class CourseDetailsAR extends FBaseActiveRecord
{
	const TABLE='course_details';

	public $uid;
	public $product_id;
	public $course_id;
	public $instructor_id;
	public $availablilitydate;
	public $student_id;
	public $estimatedcoursetime;
	public $coursesize;
	public $courseduration;
	public $expirationdate;
	public $lastlogintime;
	public $currentlogintime;
	public $coursestartdate;
	public $old_instructor_id;
	public $activated;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}