<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class CuepointAR extends FBaseActiveRecord
{
	const TABLE='cuepoints';

	public $uid;
	public $videos_id;
	public $name;
	public $description="";
	public $transcript="";
	public $start=0;
	public $stop=0;
	public $skippable=0;
	public $ishidden=0;
	public $buttonposition = 'Right bottom';
	
        public $is_enabled=1;

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
