<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class CustomerAR extends FBaseActiveRecord
{
	const TABLE='video_customers';

	public $uid;
	public $videos_id;
	public $be_users_id;
	public $name='';
	public $description='';
	public $url="";
	public $start=0;
	public $stop=0;
        public $is_enabled=1;
        public $pos=0;

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
