<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class IconAR extends FActiveLangRecord
{
	const TABLE='icons';

	public $Uid;
	public $Name;
	public $Filename;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>