<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class IconRecord extends IconAR
{
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public function getPath()
	{
		return "themes/Base/images/".$this->Filename.".jpg";
	}
	public function getColor()
	{
		return ($this->Filename)?$this->Filename:'Red';
	}
}
?>