<?php
/**
 * Auto generated by prado-cli.php on 2010-02-15 03:42:07.
 * generateAll Application.model.schema . soap F AR
 * generate table Application.model.schema.CLASS
 */
class ImprintAR extends FBaseActiveRecord
{
	const TABLE='knt_imprints';


        public $uid;
        public $name;
        public $date_created;
        public $imprint;
        public $be_user_id;
        public $client_id;
        public $client_date;
        public $branch_id;

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}