<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 *
 * CREATE TABLE `last_run_info` (
 *	`uid` int(10) NOT NULL AUTO_INCREMENT,
 *	`chapter_id` varchar(20) DEFAULT NULL,
 *	`video_id` varchar(20) DEFAULT NULL,
 *	`question_id` int(10) DEFAULT NULL,
 *	`position` int(11) DEFAULT NULL,
 *	`content_id` int(10) DEFAULT NULL,
 *	`user_id` varchar(10) DEFAULT NULL,
 *	PRIMARY KEY (`uid`)
 * ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
 *
 */
class LastRunAR extends FBaseActiveRecord
{
	const TABLE='last_run_info';

	public $uid;
	public $video_id;
	public $question_id;
	public $position;
	public $chapter_id;
	public $content_id;
	public $user_id;
	public $timestamp;
	public $subject;
	public $product_id;
	public $language;
	public $name;
	public $chaptername;
	public $ordering;
	public $blockvalue;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
