<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class OrderAR extends FBaseActiveRecord
{
	const TABLE='orders';

	public $uid;
	public $date_created;
	public $data;
	public $user_id;
	public $price;
	public $date_completed;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>