<?php
/**
 * Auto generated by prado-cli.php on 2008-10-13 12:51:06.
 */
class PostageRecord extends PostageAR 
{
	private static $cartSum=null;
        private static $cartCount=null;
	private static $_formater;
	
	public function getLimitPrice()
	{
		$app = Prado::getApplication();
		if (self::$cartSum === null)
			self::$cartSum = $app->Modules['cart']->sumCart();
			
		$limit = max((int) $app->Parameters['limitCartSum'.FU::Culture()],(int) $app->Parameters['limitCartSum']);
		return (self::$cartSum >= $limit && $limit > 0) ? 0 : $this->getFullPrice();
	}


	public function getFullPrice()
	{
		$app = Prado::getApplication();
		if (self::$cartCount === null)
                {
                    $cart = $app->Modules['cart']->getCart();
                    $c = 0;
                    foreach($cart as $item)
                        $c += $item->getCount();
                    self::$cartCount = $c;
                }

		return self::$cartCount*$this->price + $this->codlv;
	}

        public function getNameWithPrice()
	{
		$price = $this->getLimitPrice();
		if ($price)
		{
			//$this->getFormatter()->setValue($price);
			$price = "+ ".$price." ".FU::CurrencyName();//$this->getFormatter()->getFormattedValue();
		}
		else $price = Prado::localize('zdarma');
		
		return sprintf($this->name,$price);
	}
	
	public function getFormatter()
	{
		if (self::$_formater===null)
			self::$_formater = Prado::createComponent('System.I18N.TNumberFormat');
		return self::$_formater;
	}
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
