<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class ProductQuizLessonAssociationAR extends FBaseActiveRecord
{
	const TABLE='product_quiz_lesson_association';

	public $uid;
	public $quiz_settings_id;
	public $lesson_id;
	public $required_complete;
	public $markunviewed;
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
