<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class ProductLessonSettingAR extends FBaseActiveRecord
{
	const TABLE='product_lesson_settings';

	public $id;
	public $course_id;
	public $lesson_id;
	public $content_id;
	public $setting_name;
	public $setting_value;
	public $order=0;
	public $type;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}


}
