<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class ProductQuizScoresAR extends FBaseActiveRecord
{
	const TABLE='product_quiz_scores';

	public $uid;
	public $product_id;
	public $quiz_id;
	public $user_id;
	public $score;
	public $passed;
	public $resetquiz;
	public $completiondatetime;
	public $answeredpercentage;
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
