<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class ProductQuizSettingsAR extends FBaseActiveRecord
{
	const TABLE='product_quiz_settings';

	public $uid;
	public $coursecontent_id;
	public $requiredpass;
	public $passing_score;
	public $required_subsequent;
	public $post_evaluation;
	public $randomize_questions;
	public $required_complete_course;
	
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
