<?php

/**
 * Auto generated by prado-cli.php on 2009-12-13 01:51:36.
 */
class ProductQuizSequenceRecord extends ProductQuizSequenceAR {
	
    
	public static function finder($className=__CLASS__) {
	
        return parent::finder($className);
    }
}