<?php
/**
 * Auto generated by prado-cli.php on 2012-08-30 11:24:56.
 */
class ProductTimeBlocksRecord extends ProductTimeBlocksAR
{
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
