<?php

/**
 * Auto generated by prado-cli.php on 2009-12-13 01:51:36.
 */
class ProductQuizLessonAssociationRecord extends ProductQuizLessonAssociationAR {
    
	 public static $RELATIONS=array
    (
    	'settingsassociation' => array(self::BELONGS_TO, 'ProductQuizSettingsRecord', 'uid'),
    );
    
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}