<?php
/**
 * Auto generated by prado-cli.php on 2008-07-30 01:19:58.
 */
class ProductTimeBlocksAR extends FActiveLangRecord
{
	
	const TABLE='product_time_blocks';
	
	/**
	 * @var integer $uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var integer $product_id
	 * @soapproperty
	 */
	public $product_id;

	/**
	 * @var integer $video_id
	 * @soapproperty
	 */
	public $video_id;

	/**
	 * @var integer $chapter_id
	 * @soapproperty
	 */
	public $chapter_id;

	/**
	 * @var integer $starttime
	 * @soapproperty
	 */
	public $starttime;

	/**
	 * @var integer $endtime
	 * @soapproperty
	 */
	public $endtime;
	
	/**
	 * @var integer $blockno
	 * @soapproperty
	 */
	public $blockno;
	
	/**
	 * @var integer $blockcount
	 * @soapproperty
	 */
	public $blockcount;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}