<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class QuizAnswerAR extends FBaseActiveRecord
{
	const TABLE='quiz_answers';

	public $uid;
	public $quiz_id;
	public $name='';
	public $good;
	public $ordering=0;
    public $is_enabled=1;
    public $points;
    public $lang;
    public $range_limit;
	public $numeric_type;
	public $first_value;
	public $second_value;

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
