<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class QuizQuesFailureAttemptAR extends FBaseActiveRecord
{
	const TABLE='quizques_failureattempt';

    public $id;
  	public $course_instance_id;
  	public $course_id;
  	public $quiz_id;
  	public $question_id;
  	public $failureattempts;
  	
    public static function finder($className=__CLASS__) {
		return parent::finder($className);
	}
}
