<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class QuizAnswerResultRecord extends QuizAnswerResultAR
{
	const TABLE='quiz_answer_results';

	public $uid;
	public $question_id;
	public $answer_id;
	public $value;
	public $good;
	public $course_id=0;
	public $user_id=0;

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
