<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class QuizResultAR extends FBaseActiveRecord
{
	const TABLE='quiz_results';

	public $uid;
	public $quiz_id;
	public $name='';
	public $answers;
	public $ordering=0;
        public $is_enabled=1;
        public $points;
        public $lang;
        public $email;
        public $created;
        public $message;
        public $street='';
        public $zip='';
        public $city='';

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
