<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:51:36.
 */
class QuizAR extends FBaseActiveRecord
{
	const TABLE='quizes';

	public $uid;
	public $is_enabled=1;
	public $name;
	public $short_description;
	public $description;
	public $seo_keywords;
	public $date_created;
	public $date_updated;
    public $from_date=0;
    public $to_date;
	public $url1;
	public $url2;
	public $qtype='multiple choice question';
	public $hits=0;
	public $ordering=0;
	public $images;
    public $author='';
    public $category_id;
    public $parent_id;
    public $files;
    public $predefinedtask; 
    public $question_parent_id;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

}