<?php
/**
 * Auto generated by prado-cli.php on 2008-07-10 10:54:44.
 */
class SimpleCategoryRecord extends CategoryAR
{
        const TABLE = "cms_galleries_categories";
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
