<?php
/**
 * Auto generated by prado-cli.php on 2008-04-17 01:03:11.
 */
class StockAR extends FActiveLangRecord
{
	const TABLE='stocks';

	public $uid;
	public $name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>