<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class TrackingDataAR extends FBaseActiveRecord
{
	const TABLE='tracks';

	public $uid;
	public $subject;
	public $user_id;
	public $product_id=0;
	public $content_id=0;
	public $value='';


        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
