<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class TrackingDataRecord extends TrackingDataAR
{


        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
