<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:51:36.
 */
class TrainingFilesAR extends FBaseActiveRecord
{
	const TABLE='training_files';

	public $uid;
	public $user_id;
	public $username;
	public $role_id;
	public $rolename;
	public $filename;
	public $uploaddate;
	public $filesize;
    public $product_id;
    public $question_id;
    public $lesson_id;
    public $filepath;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

}