<?php
/**
 * Auto generated by prado-cli.php on 2008-01-23 12:04:58.
 * 
 * alter statement to add photo column to the table
 *ALTER TABLE `c1_video`.`be_users` ADD COLUMN `photo` LONGTEXT NULL COMMENT 'To store the image of the user. if no user is provided then default image will be used'  AFTER `branch_id` ;


 */
class UserAR extends FBaseActiveRecord
{
	const TABLE='be_users';

	public $Uid;
	public $Username;
	public $Email;
	public $Password;
	public $Role;
	public $Name;
	public $Created;
	public $Updated;
	public $Level;
	public $ReadLevel;
	public $LastIP;
	public $LastDate;
	public $Password1;
	public $Password2;
	public $Password3;
	public $LastPasswordChange;
	public $Confirmed=1;
    public $branch_id;
    public $photo='./images/noimage.png';
    public $timezone;
	public $company_id;
	public $company_level;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}