<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class UserLCommentAR extends FBaseActiveRecord
{
	const TABLE='user_lcomments';

	public $uid;
	public $videos_id=1;
	public $product_id=1;
	public $comment='';
	public $lesson='';
	public $chapter='';
	public $ordering='0000';
	public $commented_on='C';
	public $reference_id='';
	public $ts = 0;
	public $role_id;
	public $user_id;
	public $thread_id;
	public $thread_hidden;
	public $question_id;
	public $chapter_id;
	public $content_id;
    public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
