<?php
/**
 * Auto generated by prado-cli.php on 2010-02-02 01:01:58.
 * generateAll Application.model.schema . soap F AR
 * generateRec table Application.model.schema.CLASS
 */
class UserAddresRecord extends UserAddresAR
{

    private $_contacts;
    
    public static $RELATIONS=array
            (
            'roles'=>array(self::MANY_TO_MANY, 'RoleRecord', 'user_has_roles'),
            'brand'=>array(self::BELONGS_TO, 'DefinitionRecord', 'brand_id')
    );

    public function getContacts()
    {
        if ($this->_contacts === null)
        {
            $recs = ContactRecord::finder()->findAll('user_address_id = ?',$this->uid);
            foreach($recs as $rec)
            {
                $this->_contacts[] = array('name'=>$rec->type,'value'=>$rec->value);
            }
        }
        return json_encode($this->_contacts);
    }

    public function setContacts($value)
    {

        $c = json_decode($value,true);

        if (!$c) return;

        ContactRecord::finder()->deleteAll('user_address_id = ?',$this->uid);

        foreach($c as $contact)
        {
            $cc = new ContactRecord();
            $cc->type = $contact['name'];
            $cc->value = $contact['value'];
            $cc->user_id = $this->user_id;
            $cc->user_address_id = $this->uid;
            $cc->save();
        }
    }


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}