<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class UserCommentAR extends FBaseActiveRecord
{
	const TABLE='feuser_comments';

	public $uid;
	public $videos_id;
	public $feusers_id;
	public $comments='';
        public $updated=0;

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
