<?php
/**
 * Auto generated by prado-cli.php on 2008-10-20 11:24:56.
 */
class UserLCommentRecord extends UserLCommentAR
{
        public static $RELATIONS = array
        (
//        'feuser' => array(self::BELONGS_TO, 'UserFERecord', 'feusers_id'),
        'video' => array(self::BELONGS_TO, 'VideoRecord', 'videos_id'),
        );

        public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

        
}
