<?php
/**
 * Auto generated by prado-cli.php on 2010-02-15 03:42:08.
 * generateAll Application.model.schema . soap F AR
 * generate table Application.model.schema.CLASS
 */
class UserAddresAR extends FBaseActiveRecord
{
	const TABLE='user_addresses';


	/**
	 * @var integer $_uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var integer $_user_id
	 * @soapproperty
	 */
	public $user_id;

	/**
	 * @var integer $_type
	 * @soapproperty
	 */
	public $type;

	/**
	 * @var string $_description
	 * @soapproperty
	 */
	public $description;

	/**
	 * @var string $_company
	 * @soapproperty
	 */
	public $company;

	/**
	 * @var string $_address
	 * @soapproperty
	 */
	public $address;

	/**
	 * @var string $_address2
	 * @soapproperty
	 */
	public $address2;

	/**
	 * @var string $_city
	 * @soapproperty
	 */
	public $city;

	/**
	 * @var string $_country
	 * @soapproperty
	 */
	public $country;

	/**
	 * @var string $_zip
	 * @soapproperty
	 */
	public $zip;

	/**
	 * @var string $_companyID
	 * @soapproperty
	 */
	public $companyID;

	/**
	 * @var string $_vatID
	 * @soapproperty
	 */
	public $vatID;

	/**
	 * @var string $_create_date
	 * @soapproperty
	 */
	public $create_date;

	/**
	 * @var integer $_create_by
	 * @soapproperty
	 */
	public $create_by;

	/**
	 * @var string $_update_date
	 * @soapproperty
	 */
	public $update_date;

	/**
	 * @var integer $_update_by
	 * @soapproperty
	 */
	public $update_by;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}