<?php
/**
 * Auto generated by prado-cli.php on 2008-09-02 10:12:44.
 */
class VariantAR extends FBaseActiveRecord
{
	const TABLE='variants';

	public $uid;
	public $product_id;
	public $size_x;
	public $size_y;
	public $size_z;
	public $cover;
	public $price;
	public $price_sale;
	public $enabled=1;
	public $default=0;
	public $vat=19;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
