<?php
/**
 * Auto generated by prado-cli.php on 2008-07-30 01:19:58.
 * Task/Issue      Author    			    UniqueID        Comment   
 *---------------------------------------------------------------------------------------------------------------------------------------------------
 * 27659		   Arunkumar.muddada		201406050850    Added Column :$creatorname
 */
class VideoAR extends FActiveLangRecord
{
	const TABLE='videos';


	/**
	 * @var integer $uid
	 * @soapproperty
	 */
	public $uid;

	/**
	 * @var integer $parent_id
	 * @soapproperty
	 */
	public $parent_id=0;
	public $user_id=0;
	public $content_id;
	public $zones='';
	public $predefinedtask;

	/**
	 * @var boolean $is_enabled
	 * @soapproperty
	 */
	public $is_enabled=1;

	/**
	 * @var string $name
	 * @soapproperty
	 */
	public $name;

	/**
	 * @var string $short_description
	 * @soapproperty
	 */
	public $short_description;

	/**
	 * @var string $description
	 * @soapproperty
	 */
	public $description;

	/**
	 * @var string $keywords
	 * @soapproperty
	 */
	public $keywords='';

	/**
	 * @var string $date_created
	 * @soapproperty
	 */
	public $date_created=0;

	/**
	 * @var string $date_updated
	 * @soapproperty
	 */
	public $date_updated=0;

	/**
	 * @var string $url
	 * @soapproperty
	 */
	public $url='';

	/**
	 * @var boolean $is_featured
	 * @soapproperty
	 */
	public $is_featured=0;
	public $is_finished=0;

	/**
	 * @var integer $type
	 * @soapproperty
	 */
	public $type=0;

	/**
	 * @var integer $hits
	 * @soapproperty
	 */
	public $hits=0;

	/**
	 * @var integer $position
	 * @soapproperty
	 */
	public $ordering=0;
        public $cool_url='';

	/**
	 * @var string $images
	 * @soapproperty
	 */
	public $images='';
	public $files;
	public $icons='';
    public $instructions = '';
    public $company_id;
    public $chapterplaybackpause;
    public $creatorname;
   
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}