<?php
/**
 * Auto generated by prado-cli.php on 2009-12-13 01:51:36.
 */
class VideoCaptionsAR extends FBaseActiveRecord
{
	const TABLE='video_captions';

	public $uid;
	public $video_id=1;
	public $captions;
	public $language_id;
	public $name;
	public $description;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

}