
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.ux.form.field.BoxSelect": "../../../../ext/src/ux/form/field/BoxSelect1.js",
  "SWP.lib": "../../../common/lib",
  "Ext.rtl.EventObjectImpl": "../../../../ext/src/rtl/EventObject.js",
  "SWPCommon": "../../../common",
  "SWPCommon.lib.AwesomeModel": "../../../common/lib/AwesomeUploader.js",
  "SWPCommon.lib.AwesomeStore": "../../../common/lib/AwesomeUploader.js",
  " Ext.Msg": "../../../../ext/src/window/MessageBox.js",
  "Ext": "../../../../ext/src",
  "Ext.ux.layout.component.field.BoxSelectField": "../../../../ext/src/ux/form/field/BoxSelect.js",
  "Mobile": "../../../../ext/src/ux/view/animated-dataview.js",
  "SWP": "../../app",
  "Ext.ux.BoxSelect.Item": "../../../../ext/src/ux/form/field/BoxSelect1.js",
  "ImageModel": "../../../../ext/src/ux/view/data-view.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "SWP.view.comments.CommentsGridToolBar": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "SWPCommon.view.BadgeTabPanel": [],
  "Ext.ux.layout.component.field.BoxSelectField": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.BoxSelect.Item": [],
  "Ext.ux.DataView.DragSelector": [],
  "SWP.view.messaging.ShowMessagingWindow": [],
  "SWPCommon.view.BadgeTab": [],
  "SWP.view.quiz.LongRadioGroup": [],
  "SWP.Application": [],
  "SWP.store.Movies": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "SWP.store.DataGrid": [],
  "SWP.view.Tip": [],
  "SWPCommon.lib.AwesomeStore": [],
  "SWP.model.VideoCaptionSetting": [],
  "Ext.ux.PreviewPlugin": [],
  "SWPCommon.lib.AwesomeUploader": [],
  "SWP.store.Chapters": [],
  "SWPCommon.model.File": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "SWP.store.Files": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "SWP.view.Viewport": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "SWP.view.player.SWPPlayer": [],
  "Ext.ux.event.Recorder": [],
  "SWP.model.File": [],
  "SWPCommon.lib.AwesomeModel": [],
  "SWP.lib.FeedValidator": [],
  "SWP.view.player.Flowplayer": [],
  "SWP.model.LastRun": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "SWP.controller.Classroom": [],
  "Ext.ux.TabScrollerMenu": [],
  "SWP.view.chapters.List": [],
  "Ext.ux.IFrame": [],
  "SWP.view.captions.VideoCaptionSettings": [],
  "SWPCommon.model.TaskStatus": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "SWPCommon.view.BadgeButton": [],
  "SWPCommon.view.workfiles.WorkFiles": [],
  "Ext.ux.TreePicker": [],
  "SWP.view.movie.View": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "SWP.view.DataGrid": [],
  "SWP.view.comments.Grid": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "SWP.model.Chapter": [],
  "Ext.ux.GroupTabRenderer": [],
  "SWP.store.Comments": [],
  "SWP.view.quiz.Wizard": [],
  "Ext.ux.FieldReplicator": [],
  "SWPCommon.view.TableView": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "SWP.model.Video": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.XHRUpload": [],
  "Ext.ux.GMapPanel": [],
  "SWP.store.Videos": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "SWPCommon.FlexcrollAbstractComponent": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "SWP.store.LastRuns": [],
  "Ext.ux.layout.Center": [],
  "SWPCommon.store.TaskActions": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.form.field.BoxSelect": [],
  "SWPCommon.view.workfiles.FilesGrid": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "SWP.feature.GroupingBtn": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "SWPCommon.store.TaskStatuss": [],
  "SWP.store.VideoCaptionSettings": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "SWPCommon.model.TaskAction": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "SWP.model.DataGrid": [],
  "Ext.ux.DataTip": [],
  "SWP.model.Movie": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "SWP.view.Button": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "SWPCommon.view.workfiles.UploadPopup": [],
  "SWPCommon.model.Message": [],
  "SWP.model.Comment": [],
  "SWP.view.FbarButton": []
});
Ext.ClassManager.addNameAliasMappings({
  "SWP.view.comments.CommentsGridToolBar": [
    "widget.commentsgridtoolbar"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "SWPCommon.view.BadgeTabPanel": [
    "widget.badgetabpenl"
  ],
  "Ext.ux.layout.component.field.BoxSelectField": [
    "layout.boxselectfield"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.BoxSelect.Item": [],
  "Ext.ux.DataView.DragSelector": [],
  "SWP.view.messaging.ShowMessagingWindow": [
    "widget.showmessagingwindow"
  ],
  "SWPCommon.view.BadgeTab": [
    "widget.badgetab"
  ],
  "SWP.view.quiz.LongRadioGroup": [
    "widget.longradiogroup"
  ],
  "SWP.Application": [],
  "SWP.store.Movies": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "SWP.store.DataGrid": [],
  "SWP.view.Tip": [],
  "SWPCommon.lib.AwesomeStore": [],
  "SWP.model.VideoCaptionSetting": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "SWPCommon.lib.AwesomeUploader": [
    "widget.awesomeuploader"
  ],
  "SWP.store.Chapters": [],
  "SWPCommon.model.File": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "SWP.store.Files": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "SWP.view.Viewport": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "SWP.view.player.SWPPlayer": [
    "widget.swpplayer"
  ],
  "Ext.ux.event.Recorder": [],
  "SWP.model.File": [],
  "SWPCommon.lib.AwesomeModel": [],
  "SWP.lib.FeedValidator": [],
  "SWP.view.player.Flowplayer": [
    "widget.flowplayer"
  ],
  "SWP.model.LastRun": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "SWP.controller.Classroom": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "SWP.view.chapters.List": [
    "widget.chapterslist"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "SWP.view.captions.VideoCaptionSettings": [
    "widget.videocaptionsettings"
  ],
  "SWPCommon.model.TaskStatus": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "SWPCommon.view.BadgeButton": [
    "widget.badgebutton"
  ],
  "SWPCommon.view.workfiles.WorkFiles": [
    "widget.workfiles"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "SWP.view.movie.View": [
    "widget.moviesview"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "SWP.view.DataGrid": [
    "widget.datagrid"
  ],
  "SWP.view.comments.Grid": [
    "widget.commentsgrid"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "SWP.model.Chapter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "SWP.store.Comments": [],
  "SWP.view.quiz.Wizard": [
    "widget.quiz"
  ],
  "Ext.ux.FieldReplicator": [],
  "SWPCommon.view.TableView": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "SWP.model.Video": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.XHRUpload": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "SWP.store.Videos": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "SWPCommon.FlexcrollAbstractComponent": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "SWP.store.LastRuns": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "SWPCommon.store.TaskActions": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.form.field.BoxSelect": [
    "widget.boxselect"
  ],
  "SWPCommon.view.workfiles.FilesGrid": [
    "widget.filesgrid"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "SWP.feature.GroupingBtn": [
    "feature.groupingbtn"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "SWPCommon.store.TaskStatuss": [],
  "SWP.store.VideoCaptionSettings": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "SWPCommon.model.TaskAction": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "SWP.model.DataGrid": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "SWP.model.Movie": [],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "SWP.view.Button": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "SWPCommon.view.workfiles.UploadPopup": [
    "widget.UploadPopup"
  ],
  "SWPCommon.model.Message": [],
  "SWP.model.Comment": [],
  "SWP.view.FbarButton": [
    "widget.fbarbutton"
  ]
});
