<?php
/**
 * Auto generated by prado-cli.php on 2008-07-11 12:26:36.
 */
class ProductAR extends FActiveLangRecord
{
	const TABLE='products';

	public $uid;
	public $type=1;
	public $quantity=0;
	
	
	public $name;
	public $description;
	public $images;
	
	public $model;
	public $image;
	public $price=0;
	public $virtual=0;
	public $created;
	public $changed;
	public $available;
	public $weight=0;
	public $status=0;
	public $tax_class_id=0;
	public $manufacturers_id=0;
	public $ordered=0;
	public $quantity_order_min=0;
	public $quantity_order_units=0;
	public $priced_by_attribute=0;
	public $product_is_free=0;
	public $product_is_call=0;
	public $quantity_mixed=0;
	public $product_is_always_free_shipping=0;
	public $qty_box_status=0;
	public $quantity_order_max=0;
	public $sort_order=0;
	public $discount_type=0;
	public $discount_type_from=0;
	public $price_sorter=0;
	public $master_categories_id=0;
	public $mixed_discount_quantity=0;
	public $metatags_title_status=0;
	public $metatags_name_status=0;
	public $metatags_model_status=0;
	public $metatags_price_status=0;
	public $metatags_title_tagline_status=0;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>