<?php
/**
 * Auto generated by prado-cli.php on 2008-07-11 12:26:36.
 */
class ProductRecord extends ProductAR
{
	const TABLE='products';

	public static $RELATIONS=array
    (
		'categories'=>array(self::MANY_TO_MANY, 'CategoryRecord', 'products_categories')
    );

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}


    public function save()
    {
		parent::save();
		$this->saveCategories();
    }

    
    public function saveCategories()
    {
        $conn = $this->getDbConnection();
        $conn->setActive(true);
        $cmd = $conn->createCommand("DELETE FROM products_categories WHERE product_id = :prodid");
        $cmd->bindValue(':prodid', $this->uid);
        $cmd->execute();
        foreach ($this->categories as $category)
        {
	        $cmd = $conn->createCommand("INSERT IGNORE products_categories(product_id, category_id) VALUES (:prodid, :catid)");
	        $cmd->bindValue(':prodid', $this->uid);
	        $cmd->bindValue(':catid', $category->uid);
	        $cmd->execute();
		}
    }

	public function getCategoriesList()
	{
		$list = array();
		foreach($this->categories as $category)	
		{
			$list[] = (integer) $category->uid;
		}
		return $list;
	}

	public function getFirstImage()
	{
			//
		if (($list = $this->ImagesList) && $list[0]) 
		{
			
			//var_dump($list); die();
			return $list[0]->uid;
		}
		return false;
	}

	public function getImagesList()
	{
			//
		if ($this->images) 
		{
			$images = json_decode($this->images);
			return $images;
		}
		return array();
	}

	public function setCategoriesList($value)
	{
		$this->categories = array();
		$this->categories = CategoryRecord::finder()->findAllByPks($value);
	}


}
?>